/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AuthCredentialsSchema } from './models/AuthCredentialsSchema';
export type { AuthSchema } from './models/AuthSchema';
export type { BaseSettings } from './models/BaseSettings';
export type { Body_auth__logout } from './models/Body_auth__logout';
export type { Body_auth__update_tokens } from './models/Body_auth__update_tokens';
export type { Body_company__create } from './models/Body_company__create';
export type { Body_company__employee_dayoff_list } from './models/Body_company__employee_dayoff_list';
export type { Body_company__employee_list } from './models/Body_company__employee_list';
export type { Body_company__set_employee_avatar } from './models/Body_company__set_employee_avatar';
export type { Body_company__set_employee_dayoff } from './models/Body_company__set_employee_dayoff';
export type { Body_company__update } from './models/Body_company__update';
export type { Body_users__activate } from './models/Body_users__activate';
export type { Body_users__request_password_recovery } from './models/Body_users__request_password_recovery';
export type { Body_users__resend_activation_email } from './models/Body_users__resend_activation_email';
export type { BookingFilterSchema } from './models/BookingFilterSchema';
export type { BookingListSchema } from './models/BookingListSchema';
export type { BookingMasterSchema } from './models/BookingMasterSchema';
export type { BookingSchema } from './models/BookingSchema';
export { BookingSourceEnum } from './models/BookingSourceEnum';
export { BookingTypeEnum } from './models/BookingTypeEnum';
export type { ClientCategorySchema } from './models/ClientCategorySchema';
export type { ClientCommunicationWayEntity } from './models/ClientCommunicationWayEntity';
export type { ClientCommunicationWaySchema } from './models/ClientCommunicationWaySchema';
export type { ClientFilterLastVisitSchema } from './models/ClientFilterLastVisitSchema';
export { ClientFilterSchema } from './models/ClientFilterSchema';
export { ClientFilterSexEnum } from './models/ClientFilterSexEnum';
export type { ClientRelationshipDetailedSchema } from './models/ClientRelationshipDetailedSchema';
export type { ClientRelationshipSchema } from './models/ClientRelationshipSchema';
export type { ClientSchema } from './models/ClientSchema';
export { CommunicationWayEnum } from './models/CommunicationWayEnum';
export { CompanyEmployeeRoleEnum } from './models/CompanyEmployeeRoleEnum';
export type { CompanyEmployeeSchema } from './models/CompanyEmployeeSchema';
export type { CompanyEmployeeWithUserSchema } from './models/CompanyEmployeeWithUserSchema';
export type { CompanyOfficeSchema } from './models/CompanyOfficeSchema';
export type { CompanySchema } from './models/CompanySchema';
export { CompanyTypeEnum } from './models/CompanyTypeEnum';
export type { CreateBookingSchema } from './models/CreateBookingSchema';
export type { CreateClientCategorySchema } from './models/CreateClientCategorySchema';
export type { CreateClientSchema } from './models/CreateClientSchema';
export type { CreateCompanyEmployeeSchema } from './models/CreateCompanyEmployeeSchema';
export type { CreateCompanyOfficeSchema } from './models/CreateCompanyOfficeSchema';
export type { CreateEmployeeDayoffSchema } from './models/CreateEmployeeDayoffSchema';
export type { CreateScheduleShiftTimeSchema } from './models/CreateScheduleShiftTimeSchema';
export type { CreateServiceSchema } from './models/CreateServiceSchema';
export type { DeleteBookingSchema } from './models/DeleteBookingSchema';
export type { EmployeeDayoffFilterSchema } from './models/EmployeeDayoffFilterSchema';
export type { EmployeeDayoffSchema } from './models/EmployeeDayoffSchema';
export { EmployeeDayoffTypeEnum } from './models/EmployeeDayoffTypeEnum';
export { ENVEnum } from './models/ENVEnum';
export { ErrorCode } from './models/ErrorCode';
export { ErrorType } from './models/ErrorType';
export type { ErrorWrapper } from './models/ErrorWrapper';
export type { GeneralClientSchema } from './models/GeneralClientSchema';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { JWTTokenPair } from './models/JWTTokenPair';
export type { JWTTokensPairSchema } from './models/JWTTokensPairSchema';
export type { ListBookingSchema } from './models/ListBookingSchema';
export type { OfficeEmail } from './models/OfficeEmail';
export type { OfficeFeature } from './models/OfficeFeature';
export type { OfficeLink } from './models/OfficeLink';
export { OfficeLinkTypeEnum } from './models/OfficeLinkTypeEnum';
export type { OfficePhone } from './models/OfficePhone';
export type { Registration } from './models/Registration';
export type { RegistrationEntity } from './models/RegistrationEntity';
export type { ResetPasswordSchema } from './models/ResetPasswordSchema';
export type { ResponsePagingByPage } from './models/ResponsePagingByPage';
export type { ResponseWrapper } from './models/ResponseWrapper';
export type { ResponseWrapper_AuthSchema_ } from './models/ResponseWrapper_AuthSchema_';
export type { ResponseWrapper_BaseSettings_ } from './models/ResponseWrapper_BaseSettings_';
export type { ResponseWrapper_BookingSchema_ } from './models/ResponseWrapper_BookingSchema_';
export type { ResponseWrapper_ClientCategorySchema_ } from './models/ResponseWrapper_ClientCategorySchema_';
export type { ResponseWrapper_ClientSchema_ } from './models/ResponseWrapper_ClientSchema_';
export type { ResponseWrapper_CompanyEmployeeSchema_ } from './models/ResponseWrapper_CompanyEmployeeSchema_';
export type { ResponseWrapper_CompanyEmployeeWithUserSchema_ } from './models/ResponseWrapper_CompanyEmployeeWithUserSchema_';
export type { ResponseWrapper_CompanyOfficeSchema_ } from './models/ResponseWrapper_CompanyOfficeSchema_';
export type { ResponseWrapper_CompanySchema_ } from './models/ResponseWrapper_CompanySchema_';
export type { ResponseWrapper_EmployeeDayoffSchema_ } from './models/ResponseWrapper_EmployeeDayoffSchema_';
export type { ResponseWrapper_JWTTokensPairSchema_ } from './models/ResponseWrapper_JWTTokensPairSchema_';
export type { ResponseWrapper_list_app_api_http_schemas_clients_category_ClientCategorySchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_clients_category_ClientCategorySchema__';
export type { ResponseWrapper_list_app_api_http_schemas_clients_client_GeneralClientSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_clients_client_GeneralClientSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_company_company_CompanySchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_company_company_CompanySchema__';
export type { ResponseWrapper_list_app_api_http_schemas_company_dayoff_EmployeeDayoffSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_company_dayoff_EmployeeDayoffSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_company_employee_CompanyEmployeeWithUserSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_company_employee_CompanyEmployeeWithUserSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_company_office_CompanyOfficeSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_company_office_CompanyOfficeSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_schedule_booking_BookingSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_schedule_booking_BookingSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_schedule_shift_time_ScheduleShiftTimeSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_schedule_shift_time_ScheduleShiftTimeSchema__';
export type { ResponseWrapper_list_app_api_http_schemas_service_service_ServiceSchema__ } from './models/ResponseWrapper_list_app_api_http_schemas_service_service_ServiceSchema__';
export type { ResponseWrapper_ListBookingSchema_ } from './models/ResponseWrapper_ListBookingSchema_';
export type { ResponseWrapper_NoneType_ } from './models/ResponseWrapper_NoneType_';
export type { ResponseWrapper_ScheduleSchema_ } from './models/ResponseWrapper_ScheduleSchema_';
export type { ResponseWrapper_ScheduleShiftTimeSchema_ } from './models/ResponseWrapper_ScheduleShiftTimeSchema_';
export type { ResponseWrapper_ServiceSchema_ } from './models/ResponseWrapper_ServiceSchema_';
export type { ResponseWrapper_UserSchema_ } from './models/ResponseWrapper_UserSchema_';
export type { ScheduleDayEmployeeSchema } from './models/ScheduleDayEmployeeSchema';
export type { ScheduleDaySchema } from './models/ScheduleDaySchema';
export type { ScheduleFilterSchema } from './models/ScheduleFilterSchema';
export type { SchedulePeriodUpdateSchema } from './models/SchedulePeriodUpdateSchema';
export type { ScheduleSchema } from './models/ScheduleSchema';
export type { ScheduleShiftTimeFilterSchema } from './models/ScheduleShiftTimeFilterSchema';
export type { ScheduleShiftTimeSchema } from './models/ScheduleShiftTimeSchema';
export type { ServiceSchema } from './models/ServiceSchema';
export { SexEnum } from './models/SexEnum';
export type { UpdateBookingSchema } from './models/UpdateBookingSchema';
export type { UpdateClientCategorySchema } from './models/UpdateClientCategorySchema';
export type { UpdateClientSchema } from './models/UpdateClientSchema';
export type { UpdateCompanyEmployeeSchema } from './models/UpdateCompanyEmployeeSchema';
export type { UpdateCompanyOfficeSchema } from './models/UpdateCompanyOfficeSchema';
export type { UpdateEmployeeDayoffSchema } from './models/UpdateEmployeeDayoffSchema';
export type { UpdateScheduleShiftTimeSchema } from './models/UpdateScheduleShiftTimeSchema';
export type { UpdateServiceSchema } from './models/UpdateServiceSchema';
export type { UpdateUserEntity } from './models/UpdateUserEntity';
export type { UserBaseEntity } from './models/UserBaseEntity';
export type { UserSchema } from './models/UserSchema';
export type { ValidationError } from './models/ValidationError';
export { Weekdays } from './models/Weekdays';

export { AuthService } from './services/AuthService';
export { BookingService } from './services/BookingService';
export { ClientsService } from './services/ClientsService';
export { ClientsCategoriesService } from './services/ClientsCategoriesService';
export { CompanyService } from './services/CompanyService';
export { CompanyEmployeeService } from './services/CompanyEmployeeService';
export { CompanyOfficeService } from './services/CompanyOfficeService';
export { HealthcheckService } from './services/HealthcheckService';
export { ScheduleService } from './services/ScheduleService';
export { ScheduleShiftService } from './services/ScheduleShiftService';
export { ServiceService } from './services/ServiceService';
export { UserService } from './services/UserService';
